baseURL = "https://circleyellowthere.de/" #网站的URL

languageCode = "zh" #网站语言代码
title = "Circleyellowthere" #网站标题 
theme = "hugo-theme-ladder" #使用的主题名称

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  brand = "主页"
  authorDescription = " "
  info = "用我自己的眼睛去观察去感受这个世界，<br>是只有我自己才能做到的很了不起的事情"
  avatarURL = "/images/IMG_0538.png"
  favicon = "/images/avatar.PNG"
  darkModeTheme = "data-dark-mode"
disableKinds = ["RSS","taxonomy","term"]

[params.author]
name = "极品润物"
email = "Circleyellowthere@163.com"

[[menu.main]]
  name = "文章"
  url = "/blog/"
  weight = 1

[[menu.main]]
  name = "归档"
  url = "/archive/"
  weight = 2

[[menu.main]]
  name = "关于我"
  url = "/contact/"
  weight = 3

# rebuild

[build]
  writeStats = true


